/** Arabic UI strings - single locale */
export const ar = {
  nav: {
    home: 'الرئيسية',
    transactions: 'المعاملات',
    debts: 'الديون',
    settings: 'الإعدادات',
  },
  common: {
    source: 'المصدر',
    amount: 'المبلغ',
    save: 'حفظ',
    cancel: 'إلغاء',
    back: 'رجوع',
    dismiss: 'إغلاق',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    apply: 'تطبيق',
    confirm: 'تأكيد',
    unknown: 'غير معروف',
  },
  home: {
    title: 'إضافة مصروف سريع',
    addSourceHint: 'أضف مصدراً من الإعدادات لتسجيل المصروفات.',
    spend: 'صرف',
    saved: 'تم الحفظ',
    saveFailed: 'فشل الحفظ',
  },
  debts: {
    title: 'الديون',
    theyOweMe: 'هم مدينون لي',
    iOweThem: 'أنا مدين لهم',
    whoWith: 'مع من؟ (اختياري)',
    sourceForSettlement: 'المصدر (للتسوية)',
    addDebt: 'إضافة دين',
    whoPlaceholder: 'مثل: صديق، متجر',
    onHold: 'معلّق',
    out: 'خارج',
    net: 'الصافي',
    settle: 'تسوية',
    settled: 'مُسوّى',
    theyOweMeShort: 'هم مدينون لي',
    iOweShort: 'أنا مدين',
    applied: 'مُطبّق',
    noDebts: 'لا توجد ديون.',
  },
  transactions: {
    title: 'المعاملات',
    thisMonthSoFar: 'هذا الشهر حتى الآن',
    in: 'داخل',
    out: 'خارج',
    net: 'الصافي',
    deposit: 'إيداع',
    withdraw: 'سحب',
    expense: 'مصروف',
    income: 'دخل',
    depositKind: 'إيداع',
    withdrawKind: 'سحب',
    transfer: 'تحويل',
    transferBetween: 'تحويل بين المصادر',
    fromSource: 'من مصدر',
    toSource: 'إلى مصدر',
    noTransactions: 'لا توجد معاملات هذا الشهر.',
  },
  transactionTitle: 'المعاملة',
  transactionDetail: {
    type: 'النوع',
    edit: 'تعديل',
    delete: 'حذف',
    amount: 'المبلغ (د.ع)',
    source: 'المصدر',
    date: 'التاريخ',
    note: 'ملاحظة (اختياري)',
    notePlaceholder: 'ملاحظة',
    saving: 'جاري الحفظ…',
    save: 'حفظ',
    deleteConfirm: 'حذف هذه المعاملة؟',
  },
  deposit: {
    title: 'إيداع',
    amountLabel: 'المبلغ (د.ع)',
    addSourceFirst: 'أضف مصدراً من الإعدادات أولاً.',
    advanced: 'متقدم (تحويل عملة)',
    useFx: 'استخدام صرف',
    fromCurrency: 'من عملة',
    rate: 'السعر (مثلاً 1310)',
    fromAmount: 'المبلغ الأصلي (اختياري)',
    placeholder: 'مثل: 250، 500، 1,000',
  },
  withdraw: {
    title: 'سحب',
    amountLabel: 'المبلغ (د.ع)',
    addSourceFirst: 'أضف مصدراً من الإعدادات أولاً.',
    advanced: 'متقدم (تحويل عملة)',
    useFx: 'استخدام صرف',
    fromCurrency: 'من عملة',
    rate: 'السعر',
    fromAmount: 'المبلغ الأصلي (اختياري)',
    placeholder: 'مثل: 250، 500، 1,000',
    save: 'حفظ',
  },
  settings: {
    title: 'الإعدادات',
    sources: 'المصادر',
    monthlyTemplates: 'قوالب شهرية',
    newSource: 'مصدر جديد',
    newTemplate: 'قالب جديد',
    addSourceFirst: 'أضف مصدراً أولاً.',
    archive: 'أرشفة',
    archived: 'مؤرشف',
    restore: 'استعادة',
    noSourcesHint: 'لا توجد مصادر. أضف واحداً لتتبع المصروفات.',
    templateDescription: 'كل قالب يمكن أن يحتوي عدة إيرادات ومصروفات. طبّق واحداً لإنشاء كل معاملاته للشهر.',
    entriesCount: (n: number, summary: string) => `${n} عناصر (${summary})`,
    incomeCount: (n: number) => `${n} دخل`,
    expenseCount: (n: number) => `${n} مصروف`,
    templateName: 'اسم القالب',
    templateNamePlaceholder: 'مثل: ميزانية شهرية',
    entriesLabel: 'العناصر (وصف، مبلغ، مصدر)',
    entries: 'عناصر',
    income: 'دخل',
    expense: 'مصروف',
    description: 'الوصف',
    descriptionPlaceholder: 'مثل: راتب، إيجار',
    amountPlaceholder: 'مثل: 250، 500',
    active: 'فعّال',
    applyTemplate: 'تطبيق',
    applyConfirm: (n: number, name: string, month: string) =>
      `إنشاء ${n} معاملة(ات) لـ ${month} من «${name}»؟`,
    applying: 'جاري التطبيق…',
    noTemplatesYet: 'لا توجد قوالب بعد. أنشئ واحداً بعدة إيرادات ومصروفات.',
    editTemplate: 'تعديل القالب',
    editSource: 'تعديل المصدر',
    eachEntryDescription: 'كل عنصر يحتاج وصفاً',
    validAmountRequired: 'المبلغ صحيح (د.ع) مطلوب لكل عنصر',
    incomeOrExpense: 'كل عنصر يجب أن يكون دخل أو مصروف',
    atLeastOneEntry: 'أضف عنصراً واحداً على الأقل (دخل أو مصروف)',
    invalidSource: 'مصدر غير صحيح لأحد العناصر',
    nameRequired: 'اسم القالب مطلوب',
    invalidItems: 'عناصر غير صحيحة',
    sourceName: 'اسم المصدر',
    sourceNamePlaceholder: 'مثل: محفظتي، البنك',
    initialBalance: 'الرصيد الافتتاحي (د.ع)',
    initialBalancePlaceholder: '0 أو مثل: 250، 500',
  },
  sourceForm: {
    namePlaceholder: 'مثل: محفظتي، البنك',
    save: 'حفظ',
  },
  monthlyForm: {
    save: 'حفظ',
  },
  auth: {
    login: 'تسجيل الدخول',
    password: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور',
    wrongPassword: 'كلمة المرور غير صحيحة',
    logout: 'تسجيل الخروج',
    setPasswordTitle: 'تعيين كلمة مرور لهذا الجهاز',
    setPasswordHint: 'ستُستخدم لفتح التطبيق على هذا الجهاز فقط.',
    confirmPassword: 'تأكيد كلمة المرور',
    confirmPlaceholder: 'أدخل كلمة المرور مرة أخرى',
    setPassword: 'تعيين',
    passwordRequired: 'أدخل كلمة المرور',
    passwordTooShort: 'كلمة المرور قصيرة جداً (4 أحرف على الأقل)',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    setPasswordFirst: 'عيّن كلمة مرور أولاً من الرابط أدناه.',
    alreadySetHint: 'تم تعيين كلمة مرور على هذا الجهاز. أدخلها للدخول.',
    switchToEnter: 'لديك كلمة مرور؟ أدخلها',
    switchToSet: 'تعيين كلمة مرور لهذا الجهاز',
  },
  errors: {
    insufficientBalance: 'الرصيد غير كافٍ في هذا المصدر',
    somethingWrong: 'حدث خطأ',
    tryAgain: 'حاول مرة أخرى',
    serverError: 'حدث خطأ في الخادم.',
    ensureEnv: 'تأكد أن الملف .env يحتوي على',
    runDbPush: 'ثم نفّذ: npx prisma db push',
    ifJustSetup: 'إذا كنت قد أعددت التطبيق للتو، نفّذ:',
    vercelHint: 'على Vercel: أضف DATABASE_URL في Environment Variables ثم أعد النشر (يُنشئ الجداول تلقائياً عند البناء).',
  },
  amountPlaceholder: 'مثل: 250، 500، 1,000',
  amountPlaceholderIqd: 'مثل: 250، 500، 1,000 د.ع',
  month: 'الشهر',
  selectMonth: 'اختر الشهر',
} as const;
